version: 0.2
phases:
  build:
    commands:
      - sam build --parameter-overrides buildVersion=${CODEBUILD_BUILD_ID}
      - sam package --s3-bucket ${ARTIFACTS_BUCKET}
artifacts:
  files:
    - '.aws-sam/**/*'
