AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline definition with Lambda version clean up
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Git Configuration
        Parameters:
          - codestarConnectionArn
          - repository
          - branch
Parameters:
  codestarConnectionArn:
    Description: ARN of the CodeStar connection with GitHub access.
    Type: String
  repository:
    Description: Full GitHub repository name.
    Type: String
    Default: mousedownco/lambda-cleanup
  branch:
    Description: GitHub branch name.
    Type: String
    Default: main

Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub artifacts-${AWS::AccountId}-${AWS::Region}
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: ARM_LAMBDA_CONTAINER
        ComputeType: BUILD_LAMBDA_1GB
        Image: aws/codebuild/amazonlinux-aarch64-lambda-standard:nodejs20
        EnvironmentVariables:
          - Name: ARTIFACTS_BUCKET
            Type: PLAINTEXT
            Value: !Ref ArtifactsBucket
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: !Ref codestarConnectionArn
                FullRepositoryId: !Ref repository
                BranchName: !Ref branch
              OutputArtifacts:
                - Name: SourceCode
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: BuildOutput
        - Name: Deploy
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                StackName: lambda-cleanup
                TemplatePath: BuildOutput::packaged.yaml
                ParameterOverrides: '{"buildNumber": {"Fn::GetParam": ["BuildOutput", "parameters.json", "buildNumber"]}}'
                ChangeSetName: lambda-cleanup-changeset
                RoleArn: !GetAtt CloudFormationServiceRole.Arn
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                StackName: lambda-cleanup
                ChangeSetName: lambda-cleanup-changeset
              RunOrder: 2
        - Name: CleanUp
          Actions:
            - Name: CleanupLambdaVersions
              ActionTypeId:
                Category: Compute
                Owner: AWS
                Provider: Commands
                Version: "1"
              Commands:
                - export VERSIONS_TO_KEEP=3
                - echo "Will keep $VERSIONS_TO_KEEP latest versions for each function"
                - |
                  STACK_RESOURCES=$(aws cloudformation list-stack-resources \
                    --stack-name lambda-cleanup \
                    --query "StackResourceSummaries[?ResourceType=='AWS::Lambda::Function'].PhysicalResourceId" \
                    --output text)
                - |
                  for FUNCTION_NAME in $STACK_RESOURCES; do
                    echo "Cleaning up versions for $FUNCTION_NAME"

                    VERSIONS_TO_DELETE=$(aws lambda list-versions-by-function \
                      --function-name $FUNCTION_NAME \
                      --query "Versions[?Version!=\`$LATEST\`] | sort_by(@, &to_number(Version)) | [0:-$VERSIONS_TO_KEEP].Version" \
                      --output text)

                    if [ -n "$VERSIONS_TO_DELETE" ]; then
                      for VERSION in $VERSIONS_TO_DELETE; do
                        echo "Deleting version $VERSION of $FUNCTION_NAME"
                        # aws lambda delete-version --function-name $FUNCTION_NAME --qualifier $VERSION
                      done
                    else
                      echo "No versions to delete for $FUNCTION_NAME"
                    fi
                  done
              RunOrder: 1

  # Roles
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: PassRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt CloudFormationServiceRole.Arn
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
